# https://joelmccune.com/anaconda-and-arcgis-pro/
# open cmd prompt as administrator
# type conda env create -f %pathtothisfile%\environment.yml
name: arcgis

channels:
  - esri
  - conda-forge
  - defaults
  
dependencies:
  - arcgis
  - arcpy
  - nodejs
  - pyproj
  - rtree
  - shapely
  - geopandas
  - plotnine # ggplot for python
  - scikit-learn 
  - cookiecutter
  - deep-learning-essentials
  - python=3.7
  - pip
